# Use the official Node.js image as the base image
FROM node:20-alpine

# Set the working directory inside the container
RUN mkdir -p /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application to the working directory
COPY . .

# Expose the port that the server will listen on
EXPOSE 3003

# Start the server
CMD ["node", "index.js"]