# Use the official Node.js image as the base image
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the server folder to the working directory
COPY server ./server

# Build the application
RUN npm run build

# Expose the port that the server will listen on
EXPOSE 3003

# Start the server
CMD ["node", "index.js"]